- README.md
> :memo: Updated Gitter Position in Readme

- lib/autocomplete-manager.coffee
- spec/autocomplete-manager-async-spec.coffee
- spec/autocomplete-manager-autosave-spec.coffee
- spec/autocomplete-manager-integration-spec.coffee
- spec/issues/65-spec.coffee
This adds a piece of state to indicate when the suggestions should be shown.
Additionally, I've done some cleanup for consistency and clarity.
> Fix race condition with long running providers

- lib/suggestion-list-element.coffee
- spec/autocomplete-manager-integration-spec.coffee
- styles/autocomplete.less
> Highlight the matched prefix

- coffeelint.json
- lib/symbol-provider.coffee
This is based on coffeelint from core with a couple reasonalble additions.
Closes #283
> Chill the linter out a little

- lib/autocomplete-manager.coffee
- lib/suggestion-list-element.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Fix issues with specifying snippets

- appveyor.yml
- Use Chocolatey instead of the package directly
- Use full path to apm instead of setting the PATH
> Fix Appveyor CI Build

- lib/provider-manager.coffee
We dont know yet what causes #308. This should give us more information.
Closes #321
> Throw better error when scopeChain is BS

- lib/autocomplete-manager.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Strict match filter on manual activation

- lib/autocomplete-manager.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Replace suffix at the cursor when it matches the suggestion suffix

- lib/fuzzy-provider.coffee
It's already filtered by that for statement...
> Remove Duplication

- lib/suggestion-list.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Update arrow key subscriptions when suggestions length changes

- lib/suggestion-list-element.coffee
- styles/autocomplete.less
Some optimizations. Mostly centered around reading the DOM less and in the `atom.views.readDocument` method.
> Some performance fixes

- lib/main.coffee
- spec/autocomplete-manager-integration-spec.coffee
- Fixes #419
- Makes @benogle's day
> Default backspaceTriggersAutocomplete To False

- lib/suggestion-list-element.coffee
- spec/autocomplete-manager-integration-spec.coffee
Otherwise the suggestion list will resize when arrowing through the suggestions. Frustrating!
> Set suggestion list width to width of item with longest description

- spec/autocomplete-manager-integration-spec.coffee
> Fix flaky spec

- lib/autocomplete-manager.coffee
- spec/provider-api-spec.coffee
Closes https://github.com/atom-community/autocomplete-plus/issues/360
> Support `filterSuggestions` property on providers

- lib/autocomplete-manager.coffee
- lib/main.coffee
- spec/autocomplete-manager-async-spec.coffee
- spec/autocomplete-manager-integration-spec.coffee
- spec/provider-api-legacy-spec.coffee
- spec/provider-api-spec.coffee
This reduces startup time by around 30ms on my machine. Not amaze, but moves it off the list of offending packages.
> Make startup async

- README.md
This:
* Updates the Link to the Gitter room
* Simplifies content
* Updates the screenshot of the suggestion list
> Fix Link For Gitter, Update README Content

- lib/suggestion-list-element.coffee
It really bothers me that the behaviors differ between scrolling down and scrolling up.
> Scroll to selected items one by one when going up

- lib/autocomplete-manager.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Pass activatedManually To Providers In Options

- .coffeelintignore
- coffeelint.json
- lib/symbol-store.coffee
- package.json
- spec/suggestion-list-element-spec.coffee
Refs https://github.com/atom/atom/issues/5982
> Add coffeelint support

- lib/symbol-provider.coffee
- lib/symbol-store.coffee
- spec/symbol-provider-spec.coffee
> Don’t include the word under cursor when multiple cursors

- lib/suggestion-list-element.coffee
- spec/suggestion-list-element-spec.coffee
> HTML escape displayed text

- lib/provider-manager.coffee
- spec/provider-manager-spec.coffee
property of `excludeLowerPriority` is invalid.
```coffeescript
excludeLowerPriority: false
```
> Fix excludeLowerPriority bug

- lib/main.coffee
Per @benogle's suggestion in #533.
> Add File Blacklist example to Settings description

- lib/suggestion-list-element.coffee
- lib/suggestion-list.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Add support for page-up/down move-to-top/bottom

- lib/autocomplete-manager.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Dont show suggestion list when a single suggestion exactly matches the prefix

- lib/main.coffee
> Clarify description of Minimum Word Length setting

- package.json
> :art: Clean up formatting of fileBlacklist setting description

- lib/autocomplete-manager.coffee
- lib/suggestion-list-element.coffee
- lib/suggestion-list.coffee
> Remove remaining references to pane items

- lib/suggestion-list.coffee
This PR overrides any previous registered listeners to the core movement commands.
This is achieved by adding the autocompletion listener to the text editor element as the first listener as late as possible.
Depends on atom/atom#11506.
cc @nathansobo @as-cii
> Override core movement listeners

- lib/autocomplete-manager.coffee
- lib/suggestion-list-element.coffee
- lib/suggestion-list.coffee
- lib/symbol-provider.coffee
- spec/autocomplete-manager-integration-spec.coffee
- spec/fuzzy-provider-spec.coffee
- spec/main-spec.coffee
- spec/provider-api-legacy-spec.coffee
- spec/provider-manager-spec.coffee
- spec/symbol-provider-spec.coffee
- spec/symbol-store-spec.coffee
Removed unused variables and improved forward compatibility with coffee-script >=1.9.0
Similar case to atom/tabs#374
> Fix references to fields and remove unused variables

- lib/suggestion-list-element.coffee
- spec/autocomplete-manager-integration-spec.coffee
> Fix an escape bug in snippets

- lib/autocomplete-manager.js
- package.json
Also provides a config option to turn it back on. Fixes #615
> Turn off similar suggestion removal by default

- package.json
> Update fuzzaldrin-plus to 0.6.0

- spec/autocomplete-manager-integration-spec.js
- spec/spec-helper.js
This PR tries to make the failing test reported by https://github.com/atom/atom/issues/19475 a little bit more robust by making it async and making it actually wait until the autocomplete markup is detected in the DOM.
> Make failing test asynchronous
