atom/autocomplete-plus

lib/autocomplete-manager.coffee, spec/autocomplete-manager-integration-spec.coffee
This only fixes half the issue. Truly async providers will have the same problem. I'm thinking about how to solve it in that case...
=> Don’t show suggestions when they are triggered but no longer needed

lib/autocomplete-manager.coffee
The `autoActivationDelay` is the delay before displaying the list, but it is being used for an update of the results as well. When the suggestion list is open, this will use a 0 delay. It feels considerably snappier.
=> Use a 0 delay when the suggestion list is active

lib/autocomplete-manager.coffee, lib/suggestion-list.coffee, spec/autocomplete-manager-integration-spec.coffee
The backspace behavior has been really frustrating for me. I've made it so backspace cannot trigger a display, but it will stay open during backspace operations. Also, previously, it would flash (hide, then show again) on backspace, which was annoying. 
Old
New
=> Fix backspace behavior

build-package-travis-osx.sh
apm update is now an alias for apm upgrade so apm install should be used instead.
=> Change apm update to apm install

lib/autocomplete-manager.coffee, lib/suggestion-list-element.coffee, lib/suggestion-list.coffee, spec/autocomplete-manager-integration-spec.coffee
This PR subscribes to the events on the editor with a special class: `atom-text-editor.autocomplete-active`. So autocomplete will never receive focus. Since the editor retains focus, the cursor continues to blink. 
This PR has the added benefit of removing the input from the the suggestion list element. Less moving parts, and we can use the IME handling code from core, rather than our own.
=> Show cursor while autocompleting

lib/autocomplete-manager.coffee
After doing some experimentation after #226, adding a 50ms delay adds a little debouncing, while still keeping the results snappy.
=> Update 0 suggestion delay to 50

styles/autocomplete.less
Atom uses the @background-color-selected on selected list-group items, this plugin should use the corresponding text color for selection.
=> Use @text-color-selected instead

package.json
Remove `*` to reduce confusion, and add make sure atom is less than `2.0.0`.
=> Fix engines field in package.json

lib/main.coffee, lib/suggestion-list-element.coffee, spec/autocomplete-manager-integration-spec.coffee, spec/language-css-spec.coffee, styles/autocomplete.less
This allows the user to set the max number of visible suggestions, and will set the height of the suggestion box accordingly. This provides consistency across multiple editor sizes.
I've also raised the max suggestions to 200. Some providers may return many more than the visible when there is no prefix. For example ternjs:
=> Max visible suggestions option

styles/autocomplete.less
This is a continued modification of the colors to allow for all variants of highlight and selected colors set by the theme.
Here's sample colors in One Dark, Atom Light, One Light, and Unity.
=> More correct use of theme colors

lib/autocomplete-manager.coffee, lib/main.coffee, lib/suggestion-list-element.coffee, package.json, spec/autocomplete-manager-integration-spec.coffee, styles/autocomplete.less
Merge when atom 0.183.0 is out
This PR seeks to integrate autocomplete-plus with [snippets](https://github.com/atom/snippets) such that snippets.insert can be used to dynamically insert anonymous snippets into the current editor. This will allow autocomplete-plus providers to include anonymous snippets as part of their suggestions, giving a richer experience (particularly when confirming a suggestion which is a function, allowing us to expand the arguments automatically and allow the user to tab through them).
See https://github.com/atom/snippets/pull/106 / https://github.com/atom/snippets/pull/110
=> Consume Snippets API

lib/autocomplete-manager.coffee, lib/provider-manager.coffee, package.json
* Defer minimatch require so it is only loaded when a blacklist exists
* Only require the active symbol provider instead of both
* Move `temp` to a dev dependency
* Remove unused `grim` dependency
=> Defer requires

lib/main.coffee
I noticed my config was getting saved each time Atom started up and traced it to this check.
If people installed `autocomplete-plus` after this config was migrated (I did), then `oldMax` would be null and the migration would occur each time the package was activated.
/cc @benogle looks like this changed in https://github.com/atom-community/autocomplete-plus/pull/272
=> Only migrate config when it exists

lib/autocomplete-manager.coffee
This takes part of #294 and separates it out for immediate merge. This allows providers to get a suggestion request if someone types `(`, `[`, etc. and bracket matcher inserts the corresponding `)`, `]`, etc.
=> Allow Auto Activation When Bracket Matcher Automatically Inserts A Match

lib/main.coffee
Exactly as it says in the commit message. Fixes a spelling mistake in main.coffee by changing "appers" to "appears".
=> Fix spelling of appers to appears

lib/fuzzy-provider.coffee, lib/provider-manager.coffee, lib/provider-metadata.coffee, lib/scope-helpers.coffee, lib/symbol-provider.coffee, package.json, spec/provider-manager-spec.coffee
Use of the scoped property store was complex and confusing. This PR takes a much more straightforward approach to storing and filtering the providers. 
Other things improved:
* Specificity sorting uses real specificity
* Sorting of providers is stable, so providers added later will come later when specificities are equal.
=> Remove the scoped property store

lib/suggestion-list.coffee, spec/autocomplete-manager-integration-spec.coffee
There were some issues when `suggestionListFollows` is `Word`
* The markers created were never destroyed!
* The marker was added to the subscriptions, but it does not have a dispose method. So on deactivate, there was an exception.
* There were no specs
=> Fix issues when suggestionListFollows is `Word`

lib/autocomplete-manager.coffee
This was only in there for the autocomplete-snippets package, which now expands on its own.
=> Remove auto-snippet-expansion when `isSnippet` is defined

lib/autocomplete-manager.coffee, lib/main.coffee, spec/autocomplete-manager-async-spec.coffee, spec/autocomplete-manager-integration-spec.coffee, spec/issues/52-spec.coffee
- Also allow space to trigger autocomplete
- Compare against an array of bracket-matcher pairs
- Only inspect newText / oldText when autoActivationEnabled
@benogle this might still feel like a hack, but it doesn't create two garbage arrays on each keystroke.
=> Attempt To Clean Up Bracket Matcher Accommodation

lib/autocomplete-manager.coffee, spec/autocomplete-manager-integration-spec.coffee
Previously, you could add several cursors, trigger autocomplete, and it would replace prefixes that had the same length, even when the prefixes didnt match. 
cc @nathansobo as this will no longer merge selections.
=> Only replace replacementPrefix when it matches text before cursor

lib/autocomplete-manager.coffee, spec/autocomplete-manager-integration-spec.coffee
* The suggestion box would close when typing subsequent characters
* When manual mode is triggered and there is only one suggestion, dont show the UI, just confirm it.
@nathansobo can you get this branch and try it out?
TODO (maybe)
=> Improve for manual activation

lib/autocomplete-manager.coffee
This patch prevents autocomplete from triggering when in vim-mode "command" (normal) mode (e.g. when pressing `x`).
=> If vim-mode is active, activate autocomplete only in insert mode

lib/autocomplete-manager.coffee, lib/main.coffee, spec/autocomplete-manager-integration-spec.coffee
This is an initial attempt at suppressing activation for vim-mode when insert-mode is active, but in a way that is configurable and extensible.
@benogle thoughts on how we might test for this without explicitly requiring vim-mode to be installed for a developer or the CI builds?
=> Suppress Activation For EditorView Classes

lib/autocomplete-manager.coffee, lib/suggestion-list-element.coffee, lib/suggestion-list.coffee, spec/autocomplete-manager-integration-spec.coffee
This will align the replacement with the prefix when `suggestionListFollows` is 'Word'.
=> Align replacement to prefix when suggestionListFollows is 'Word'

lib/symbol-provider.coffee, lib/symbol-store.coffee, spec/symbol-provider-spec.coffee
It would return the word under the cursor in the suggestion list:
=> Fix SymbolProvider to not return the word under cursor

lib/main.coffee, lib/suggestion-list.coffee, spec/autocomplete-manager-integration-spec.coffee
I'm not sure why custom commands were being used to navigate the suggestion list. I think ideally, it should work with whatever you have mapped to core:move-up/down.
=> Use core:move-up/down rather than custom select-prev/next commands

lib/suggestion-list-element.coffee, spec/autocomplete-manager-integration-spec.coffee, spec/provider-api-spec.coffee, styles/autocomplete.less
This is a continuation of #356. My work adds on with:
* Always display at the bottom of the list, even when scrolling
* Style the description
* Add a `descriptionMoreURL` option to add a more link
* Specs 
After using it and messing with it, I made a couple new decisions:
* Instead of a single line, I want to allow multiline initially. Hopefully people keep things reasonable
* Rather than markdown, authors can specify a `descriptionMoreURL` option to their suggestions. When this is present, it will display the more link. This should keep things uniform. 
Light:
Dark: 
Closes #356 
Closes #209
=> Suggestion descriptions

lib/fuzzy-provider.coffee, lib/symbol-provider.coffee, lib/symbol-store.coffee, spec/fuzzy-provider-spec.coffee, spec/symbol-provider-spec.coffee, spec/symbol-store-spec.coffee
This rounds out the config API for the symbol provider. I am overloading / co-opting `editor.completions` setting to accept the symbol provider config. Language packages will be able to specify a config like this:
```coffee
'.source.coffee':
editor:
completions:
class:
selector: '.class.name, .inherited-class, .instance.type'
typePriority: 4
function:
selector: '.function.name'
typePriority: 3
variable:
selector: '.variable'
typePriority: 2
'':
selector: '.source'
typePriority: 1
builtin:
suggestions: [
'one'
'two'
]
```
The old completions array will still work:
```coffee
'.source.coffee':
editor:
completions: [
'one'
'two'
]
```
The `FuzzyProvider` will do what it's always done, and the `SymbolProvider` will add the completions with `type: 'builtin'`.
Note: using the overloaded …
=> Config API changes for SymbolProvider

lib/symbol-provider.coffee, lib/symbol-store.coffee, spec/symbol-provider-spec.coffee, spec/symbol-store-spec.coffee
With this PR, the list of symbols will only be generated once for each open file: on file open (welllll, on retokenization too, but that is infrequent). 
This keeps the `SymbolStore` up to date with all the symbols for all open buffers as the open buffers change; it keeps track of the position (buffer row) of each symbol in each open file. One `Symbol` object is stored for each unique symbol.
Why do this? Regeneration on save and when switching buffers is laggy. It gets even more laggy when there are multiple open largish files and you have `includeAllOpenBuffers` on. Reading the symbols once, then consuming the localized changes is ideal. 
Note that this is optimized for returning the results of all open buffers: It tracks all open buffers all the time. It tracks all of them because …
=> SymbolProvider: No longer rengenerate the symbol list when saving or switching buffers

lib/suggestion-list-element.coffee, lib/symbol-provider.coffee, spec/provider-api-spec.coffee, spec/suggestion-list-element-spec.coffee
The `displayText` will take display precedent over both `text` and `snippet`.
=> Accept `displayText` property in suggestion object

lib/symbol-provider.coffee, spec/symbol-provider-spec.coffee
It was under `editor.completions`, and now it is under `autocomplete.symbols`.
=> Move symbol config to autocomplete.symbols

lib/suggestion-list.coffee, lib/symbol-provider.coffee, spec/autocomplete-manager-integration-spec.coffee, styles/autocomplete.less
=> Fix small things that came up when updating autocomplete-css and autocomplete-html

package.json
This changes `licenses` to `license` in `package.json` as this is what npm's (and what we're now using) `normalize-package-data` expects. Atom specs will now fail without it :grin:
=> Change licenses field to license

lib/autocomplete-manager.coffee
This is to fix some breakage against Atom master. Recent [changes](https://github.com/atom/text-buffer/pull/58) to `text-buffer` have affected the order in which markers' `onDidChange` events are emitted, relative to the buffer's `onDidChange` event. Now, marker events are always emitted after buffer events. At first I interpreted this as a bug in `text-buffer`, but now I don't think it is.
This package uses the `Cursor::onDidChangePosition` and `Buffer::onDidChange` hooks to show and hide the autocomplete view, in a way that depends on the order in which they occur. I don't fully understand the chain of events (maybe @joefitzgerald or @benogle will understand this better) but I found that in some cases, in the `Buffer::onDidChange` handler, we were deciding *not* to show the autocomplete …
=> Check all cursors (not just last) when deciding whether to activate

lib/symbol-provider.coffee, lib/symbol-store.coffee, spec/symbol-store-spec.coffee
This doesn’t add much speed, but it avoids the allocation of arrays of temporary token objects which should avoid GC pauses. It will work on version of Atom where the token iterator is available on TokenizedLine (see atom/atom#6757)… otherwise it falls back to the `tokens` property.
/cc @benogle
=> Use token iterator rather than tokens shim on TokenizedLine if available

lib/suggestion-list-element.coffee, spec/autocomplete-manager-integration-spec.coffee
It would scroll the workspace in some cases. No bueno. This new way feels better anyway.
Closes #511
Closes #505
=> Remove the native scrollIntoView() call.

README.md
Took me a little while to track this down (I was trying just extensions, without the `*` matching). Not sure if the Readme is the right place for this, or perhaps I should add the example to the Settings description?
=> Readme update: add example for file blacklisting

README.md, keymaps/autocomplete-plus.cson, lib/main.coffee, lib/suggestion-list.coffee, spec/autocomplete-manager-integration-spec.coffee, spec/spec-helper.coffee
The instructions in the readme dont work for people who want to remap the movement commands. `unset!` doesnt actually do what users want, so up/down, and the others are not able to be remapped. This PR adds a `useCoreMovementCommands` setting that will listen for `autocomplete-plus:*` commands rather than `core:*` events when disabled. Instructions also added to the readme. 
cc @joefitzgerald @lee-dohm I know people have problems with this, and this is an attempt to give folks a clean way to remap.
=> Add setting to allow for remapping of keybindings

lib/symbol-store.coffee
I've recently been experiencing multi-second pauses in longer-running Atom sessions (or possibly sessions with large numbers of open files). I'm unable to reproduce shortly after restarting, so the primary cause of my pauses is likely elsewhere. However, the attached fix seems to help significantly. The source of the pause in the attached profile is [implicit list comprehensions](https://github.com/jashkenas/coffeescript/issues/896).
The inner loop of `Symbol.appliesToConfig` looks like this:
```coffeescript
@metadataByPath.forEach ({scopeChains}) =>
for scopeChain, __ of scopeChains
if (not @type or options.typePriority > typePriority) and selectorsMatchScopeChain(options.selectors, scopeChain)
@type = type
typePriority = options.typePriority
```
and compiles to this:
```javascript …
```
=> Avoid implicit list comprehension in Symbol.symbolsForConfig

lib/scope-helpers.coffee, lib/symbol-store.coffee
When we have a large number of symbols in the symbol store due to a large file being opened and tokenized, computing suggestions gets expensive due to matching selectors in the symbols against the current scope in a tight loop. Long term, we need to compute the type of a symbol once upon insertion into the symbol store, but this PR caches the selector matches to at least minimize the work being performed in the loop on subsequent completions for the same scope.
This profile was performed by opening `text-editor-spec.coffee` and `huge.js` in an editor and allowing both to tokenize. Then I typed at the end of the file, typed in a string to bust the existing caching, then switched back to the end of the file and typed more. With the new caching, subsequent completions are about ~5x faster, …
=> Cache and micro-optimize suggestion generation in SymbolProvider

lib/autocomplete-manager.coffee, lib/main.coffee, spec/autocomplete-manager-integration-spec.coffee
Allows disabling automatic confirm a singular suggestion when in manual
mode. Useful if this match is wrong or using manual completion to see
function signature.
=> Add 'enableAutoConfirmSingleSuggestion' setting

lib/autocomplete-manager.coffee, lib/main.coffee, spec/autocomplete-manager-integration-spec.coffee
Adds the option:
Which, when disabled, ignores any suffix text.
Closes #468
Closes #559
=> Adding an option to toggle the consumption of suffix characters

spec/autocomplete-manager-integration-spec.coffee
Refs.: atom/atom#8811
We're enabling subpixel font scaling and, although this package doesn't make use of it directly, some of its tests rely on it, thus breaking in the aforementioned PR. 
Specs fail on atom/atom :x: because we always round positions to the nearest integer. This PR fixes it by always checking for rounded positions.
(AppVeyor is failing for some reason, although [specs are :green_heart: in there as well](https://ci.appveyor.com/project/joefitzgerald/autocomplete-plus/build/725).)
/cc: @nathansobo
=> Round left position to the nearest integer

lib/autocomplete-manager.coffee, lib/main.coffee, lib/suggestion-list-element.coffee, lib/symbol-provider.coffee, package.json
Closes https://github.com/atom/autocomplete-plus/issues/586
Add options to the end:
Use Alternative Scoring - disabled by default, use fuzzaldrin-plus.
Use Buffer Proximity - enabled by default, standard locality scoring.
This is done so the tester can see the effect of which is which. 
They are not quite tuned together. 
Example when proximity feel intuitive or not would be helpful, there's no spec for that.
Maybe later proximity strength  can be an option instead of on/off.
=> Use fuzzaldrin-plus as an option

lib/autocomplete-manager.coffee, lib/fuzzy-provider.coffee, lib/symbol-provider.coffee
We've introduced a new function to understand whether an object is a `TextEditor` or not in https://github.com/atom/atom/pull/9711.
This PR makes use of it to fix #614.
/cc: @benogle @atom/feedback
=> Use atom.workspace.isTextEditor when available

lib/main.coffee
While working with `autocomplete-plus` I tried to blacklist both `*.md` and `*.txt` but I failed to do so, because I was expecting that ` ` (space) would be a valid separator. Explaining a bit more what the _File Blacklist_ option expects would have saved me some time...
=> Explain how to use mulitple file blacklist items

lib/autocomplete-manager.coffee, spec/autocomplete-manager-integration-spec.coffee
This avoids overwriting characters in `editor.nonWordCharacters` when they follow the cursor and match a suffix of the autocomplete text.
This mainly comes up when the replacement text is a function call ending with `)`. Currently, when a `)` *already* follows the cursor, it gets overwritten by the autocomplete text, which is usually not what the user wants.
Refs https://github.com/atom/autocomplete-plus/pull/628
/cc @benogle @nmote
=> Don't overwrite non-word characters that match replacement suffixes

lib/main.coffee, package.json, spec/provider-api-spec.coffee, spec/symbol-provider-spec.coffee
For some reason the request to update ac+ got translated to command palette.
Probably not bad but this still need to be done.
@benogle @nathansobo
=> use fuzzaldrin-plus by default

lib/autocomplete-manager.coffee
Added an instruction to trigger the auto indentation after a suggestion is confirmed. 
(It is a bugfix for [this](https://github.com/atom/autocomplete-plus/issues/610) issue)
=> bugfix: auto indentation after suggestion confirm

lib/suggestion-list-element.coffee
See https://github.com/atom/atom/issues/8295#issuecomment-165112901 for more information about why this happens.
With this PR we prevent margins to be adjusted across two different animation frames, which causes the autocompletion box to flicker.
/cc: @benogle for :eyes:
=> Stop flickering when adjusting margins

lib/autocomplete-manager.coffee
Depends on atom/text-buffer#127.
Before:
After:
It now takes `~2ms` instead of `~585ms`. :racehorse: :chart_with_upwards_trend: 
@benogle: I'd :heart: to have your feedback on this. It seems like a 100% backwards-compatible and behavior-preserving change, but some more pair of :eyes: on this would be awesome. :pray: 
/cc: @nathansobo @maxbrunsfeld @kuychaco
=> Batch autocompletion show/hide

lib/symbol-store.js
Closes #679. I believe that was caused by the stack growing because of `Array.prototype.splice` that requires the `...` operator, hence making the parameter list humongous.
/cc: @benogle
=> Fix maximum call stack size exceeded error

lib/symbol-provider.coffee, lib/symbol-store.js
We still use a private API, `TokenizedBuffer.prototype.tokenizedLineForRow` but we avoid accessing the `TextEditor.prototype.displayBuffer` property in versions of Atom where doing so triggers a deprecation warning. This is a backward compatible change.
=> Avoid deprecations introduced in atom/ns-use-display-layers branch

lib/autocomplete-manager.coffee, lib/fuzzy-provider.coffee, lib/provider-manager.coffee, lib/provider-metadata.coffee, lib/symbol-provider.coffee, spec/provider-api-legacy-spec.coffee, spec/provider-api-spec.coffee, spec/provider-manager-spec.coffee
Currently, only `TextEditors` that are items of `Panes` are observed.
With atom/atom#10851, observing all `TextEditors` will be supported, which the `autocomplete-manager` will use with this PR.
To then provide autocompletion in various `TextEditors` (e.g. in `find-and-replace`), a `Provider` should be able to specify to which `TextEditor` it applies.
This PR implements that by allowing the `Provider` to specify a CSS selector for the `TextEditorElement` to which it should apply.
The default will be set to `atom-pane > .item-views > atom-text-editor` for backwards compatibility.
This will support the use case mentioned in #383.
/cc @benogle
=> Observe the TextEditorRegistry, constrained by a CSS selector.

lib/main.coffee, lib/private-symbols.coffee, lib/provider-manager.coffee, lib/provider-metadata.coffee, package.json, spec/provider-api-legacy-spec.coffee, spec/provider-manager-spec.coffee
@as-cii, @wvanlint I decided we should only show deprecation warnings when someone is trying to use the new feature and there is ambiguity. So this adds a 2.1 service endpoint. To get the text editor selector you have to use it. If you use it you'll get deprecation warnings with the old field names. Still need to update documentation.
=> Add 3.0 service endpoint which exposes `textEditorSelector`

lib/suggestion-list-element.coffee, lib/suggestion-list.coffee, package.json, spec/autocomplete-manager-integration-spec.coffee
This introduces a new setting which will enable alternate behaviour for `Enter` when the suggestion list is opened:
- If the default suggestion is selected, `Enter` will pass through and insert a linebreak. `Tab` will still insert that suggestion.
- If the selected suggestion has been changed by some means, e.g. `Cursor down`, `Enter` will insert that suggestion, just like `Tab`.
I'm totally open to suggestions regarding method names and the setting description. Also, I don't have much experience with the specs, but I *think* they should test what I want them to. :)
=> Alternate completion keybinding behaviour

lib/suggestion-list-element.coffee, styles/autocomplete.less
Fixes [#728](https://github.com/atom/autocomplete-plus/issues/728)
This PR includes a simple change to move the right-label span up one level so that it will be displayed as a `table-cell` instead of using `float: right`. This fixes layout problems by ensuring that the right label always has enough space reserved to avoid lines shifting down.
Before change:
After change:
After change, with a really long suggestion:
=> Fixes #728 - Use table-cell display for right label

CONTRIBUTING.md, package.json
Two tiny fixes for dead URLs:
1. URL for scopes displayed within settings
2. URL for Atom Contributing Guidelines
=> URL updates

lib/autocomplete-manager.coffee
Passing in `undefined` to `path` module functions results is no longer supported as of Node v6. This PR is part of the effort to upgrade Atom to run on the latest release of Electron (atom/atom#12300).
=> Guard against undefined path

lib/fuzzy-provider.coffee, lib/symbol-provider.coffee, spec/fuzzy-provider-spec.coffee, spec/symbol-provider-spec.coffee
After an editor has been created and its lines tokenized, we were previously scanning the entire buffer to search for symbols or fuzzy provider tokens. This operation could be quite expensive, and its cost grew linearly with the size of the file. 
*(Benchmark performed by opening [big.txt](https://github.com/atom/autocomplete-plus/files/523872/big.txt), 5.2MB)*
With this pull request, when `largeFileMode` is detected, we simply avoid scanning the buffer, which makes opening files larger than 2MB significantly faster. In the future, we might also improve this further for files smaller than 2MB by recomputing symbols or fuzzy provider tokens in chunks via request idle callbacks.
For now, in conjunction with https://github.com/atom/atom/pull/12933, this should fix all the remaining large …
=> Don't recompute symbols or fuzzy provider tokens when `editor.largeFileMode` is on

lib/autocomplete-manager.coffee, spec/autocomplete-manager-integration-spec.coffee, spec/provider-api-legacy-spec.coffee
This pull request fixes two deprecations that will be added as part of the shadow DOM removal:
1. Instead of relying on `document.activeElement` returning an `atom-text-editor` element, it now uses the `closest` API instead. 
2. It replaces usages of `TextEditorElement.prototype.shadowRoot` with the editor element itself.
/cc: @atom/core
=> Fix shadow DOM removal deprecations

lib/symbol-store.js, spec/symbol-store-spec.coffee
Given
* you set some completions in settings.cson in  'autocomplete' -> 'symbols' -> 'builtins' -> 'suggestions' section ([example](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/settings/language-1c-bsl.cson#L21))
---
When
* you type this function first time
Then
* you'll see a `b` mark and a description
When
* you type this function *not* first time
Then
* you'll see no mark or description
---
With this PR:
=> Fix type of seen suggestions

lib/autocomplete-manager.js, lib/suggestion-list-element.js, package.json, spec/autocomplete-manager-integration-spec.js
This PR adds support for supplying markdown in descriptions of suggestions. It supersedes #733 which originally allowed HTML to be specified.
Fixes #423 
Fixes #626 
Closes #733
=> Add descriptionMarkdown option to specify markdown in desriptions

package.json
This PR lowers the default `autoActivationDelay` setting from 100ms to 0ms, which - for the vast majority of users - will have the effect of making autocomplete feel "snappier". This introduces the risk that an errant autocomplete provider could affect typing performance, if it is synchronous and locks up the thread. This risk is countered by the fact that the API is promise based, and if node's main thread locks up (promise or otherwise) then there is a bigger issue for which this timeout value will be irrelevant.
- In retrospect, this was premature optimization; the API is promise-based, and providers should not be doing synchronous work
- The net effect of setting the default autoActivationDelay to 100 is that users perceive the performance of autocomplete-plus to be less favorable …
=> Reduce default autoActivationDelay from 100ms to 0ms

lib/autocomplete-manager.js, lib/main.js, lib/provider-manager.js, lib/suggestion-list-element.js, lib/suggestion-list.js, spec/autocomplete-manager-async-spec.js, spec/autocomplete-manager-autosave-spec.js, spec/autocomplete-manager-integration-spec.js, spec/provider-api-legacy-spec.js, spec/provider-api-spec.js, spec/suggestion-list-element-spec.js
This pull request stops registering custom elements during startup and uses simple javascript objects that internally manage a DOM element instead.
/cc: @ungb for 👀
=> Stop registering SuggestionListElement as a custom element

styles/autocomplete.less
- Restricting to 800px is unnecessarily small on large displays
- Restricting the size of different portions of the suggestion list (left / word / right) results in unnecessary truncation of text
- It just looks nicer 😄 
Before:
After:
/cc @AndreaGriffiths11 @ungb @nmote 
- Fixes #670 
- Fixes #566 
- Fixes https://github.com/joefitzgerald/go-plus/issues/504
- #389 worth testing for
=> Allow suggestion list to use 75% of viewport width

styles/autocomplete.less
This raises the `z-index` to `12`.
Fixes the docks border from being on top.
Now autocomplete might cover other things. Tooltips and modals seem fine, tough.
Fixes #834
=> Raise z-index

spec/autocomplete-manager-integration-spec.js
The `TextBuffer.save` method is going to become async in https://github.com/atom/atom/pull/14435; instead of doing a synchronous write, it will initiate an asynchronous write and return a promise when the write completes. This shouldn't affect the user-facing functionality of many packages; but several packages may have test failures.
This updates the one test in `autocomplete-plus` that broke due to this change to work regardless of whether `save` is synchronous or asynchronous.
=> Adjust test to work when TextBuffer.save is made async

spec/autocomplete-manager-integration-spec.js, styles/autocomplete.less
This increases the minimum width from `200px` to `243px`.
Before | After
--- | ---
~~Many alternatives would be possible, but 250 seems a nice number.~~
Actually, specs failed with `250px`, so after some trial and error, `243px` seems to pass.
Makes sure the description isn't too narrow and hard to read.
Covers more of the horizontal code.
Based on [this feedback](https://github.com/atom/autocomplete-plus/pull/827#issuecomment-297872777).
=> Increase min width

lib/suggestion-list.js, spec/autocomplete-manager-integration-spec.js
When `autocomplete.suggestionListFollows` is set to `"Cursor"`, the overlay decoration was being destroyed prematurely in `showAtCursorPosition()`. Only destroy the existing overlay if the Editor has changed and we're about to create a new one.
Fixes #850 with a hat tip to @50Wliu for doing the initial investigative work :smile:
=> Prevent premature suggestion list closing when following cursor

lib/provider-manager.js, spec/provider-manager-spec.js
This change:
- Implements the ability to add listeners for when autocompletion providers are added or removed.
- Exposes the default autocompletion provider.
This is an implementation of the proposal in atom/find-and-replace#710 from @as-cii.
Autocompletion providers can be more reliably accessed when they are added or removed. The default autocompletion provider can be identified without introspection.
=> Listeners for provider additions and removals

README.md, lib/autocomplete-manager.js, lib/fuzzy-provider.js, lib/provider-manager.js, lib/provider-metadata.js, lib/symbol-provider.js, spec/autocomplete-manager-integration-spec.js, spec/provider-api-legacy-spec.js, spec/provider-api-spec.js, spec/provider-manager-spec.js
Branched from #867.
This change introduces labels for autocompletion providers.
Editors can sign up for autocompletions from providers with a given list of labels.
If not set, the labels for a provider will default to `['workspace-center']` and the main workspace text editors will automatically receive autocompletions from providers with this label.
=> Labels for autocompletion providers that editors can subscribe to

lib/autocomplete-manager.js, lib/provider-manager.js, lib/provider-metadata.js, lib/symbol-provider.js, spec/provider-api-legacy-spec.js, spec/provider-api-spec.js, spec/provider-manager-spec.js
This reverts pull request #676 in preparation of providing a service
that can enable autocompletion for a given text editor.
=> Revert observing all editors

lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js
This PR changes the method of observing the pane item editors from `observeActiveTextEditor` with `updateCurrentEditor` to `observeTextEditors` with `watchEditor`.
The focus can indeed move between editors without `atom.workspace.getActiveTextEditor` changing, which is why focus listeners are necessary.
Also adds a blur listener so the autocompletions are hidden when switching focus.
=> Adjustments to observing text editors and listening for focus

lib/autocomplete-manager.js, lib/main.js, lib/provider-manager.js, lib/suggestion-list.js, spec/provider-manager-spec.js
Previously, we were deferring the construction of the `AutocompleteManager` via a `setImmediate` callback in an attempt to reduce this package's impact on startup time. Unfortunately, all this really did was **hide** this package's impact on startup time, because the `setImmediate` was still getting called before the first paint, as you can see below:
In #873, @wvanlint is opening up a service that allows other packages to register editors for autocomplete support. Constructing the `AutocompleteManager` asynchronously is complicating the interface of that service. This change should make that service much simpler with a synchronous API while not actually detracting from real-world startup time. We should revisit the initialization code path to see if we can actually make it faster rather …
=> Remove asynchronous construction of AutocompleteManager

README.md, lib/autocomplete-manager.js, lib/main.js, package.json
Provides a service that exposes the `AutocompleteManager` in an asynchronous way.
I'm not convinced on the naming so let me know if you have any suggestions.
=> Provide the watchEditor method as a service

styles/autocomplete.less
Completion proposals may have a lot of text in the description or rather descriptionMarkdown field. Since there is no max-height CSS style (and other related CSS attributes overflow-y etc) the height on suggestion-description the description may become very long in y direction.
I have set the `max-height` attribute for the `description-content` span and then had to set `display: block` which mean that it may just become a `div` instead of `span` perhaps.
This is the related issue: https://github.com/atom/autocomplete-plus/issues/870
=> Completion description style

lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js
Currently, if the suggestion list is displayed, and the user enters a newline or a space, we hide (i.e., dismiss) the suggestion list. That makes sense, and we want to retain that behavior. However, if a text change occurs _elsewhere_ in the buffer (e.g., automated tooling that adds semicolons at the end of each line in a JavaScript file as you're typing), that change shouldn't interfere with a human user interacting with the autocomplete suggestion list.
With the changes in this PR, we only hide the suggestion list if a text change occurs at the cursor where the human user is interacting with the autocomplete selection list.
=> Text changes *elsewhere* in buffer should not hide selection list at cursor

lib/provider-config.js, lib/provider-manager.js, lib/subsequence-provider.js, package.json, spec/subsequence-provider-spec.js
I wanted to get this up for feedback sooner rather than later.
This adds the subsequence provider which uses the soon-to-be-merged
`findWordsWithSubsequence` method on `TextBuffer` https://github.com/atom/superstring/pull/22. I've also moved all the logic about the provider config into its own class. 
I've just copied to tests over from the symbol provider and added a few where it made sense.
`SymbolProvider` and `FuzzyProvider` store token lists that have to be created when new buffers load and kept in sync with buffer changes. This can be somewhat slow and happens on the main thread--often causing long frames.
Using the `findWordsWithSubsequence` on `TextBuffer` does the work of finding matches in a separate thread never blocking a render (yay performance!) and greatly simplifies the …
=> add subsequence provider

lib/subsequence-provider.js
fix https://github.com/atom/autocomplete-plus/issues/898
=> remove use of regex in strict matching

lib/suggestion-list-element.js, lib/suggestion-list.js
When the suggestion list first appears, the the `SuggestionListElement` render method is being called twice in a single frame. I think maybe this was put in place to ensure that the suggestion list always appears with the latest suggestions. I've noticed that the suggestion list generally appears to be correct without the calls to `didAttach`. However, there is one problem I've been able to reproduce. After a reload, on the first key stroke, I get
I'll try to see if I can resolve this without introducing a second call to `.render`. Does anyone know off the top of their head if there are any other issues with removing this?
=> remove didAttach which causes SuggestionListElement to render twice

lib/suggestion-list-element.js, spec/suggestion-list-element-spec.js
This PR moves away from setting `.innerHTML` in `.renderItem` where possible. Though, when we receive HTML via the suggestion provider API, we still have to use it. Direct DOM manipulation tends to be faster when called in a loop:
Here's an illustration of the improvement for the same autocomplete scenario before and after the changes in this PR:
n/a
This is a step towards faster rendering of autocomplete suggestions making the typing experience feel more responsive.
Imperative dom manipulation can potentially be more complex than just setting `.innerHTML` in some cases.
n/a
=> Move towards more efficient DOM manipulation

lib/subsequence-provider.js, spec/subsequence-provider-spec.js
Recently, we added a change in https://github.com/atom/superstring/pull/37/files to remove a sorting ambiguity that occurred when scores tied. This has the added benefit of returning the shorter word first when scores tie. The change in this PR applies the same sorting scheme after the results from all buffers are merged together. This should fix item#1 in https://github.com/atom/superstring/issues/36.
n/a
It's more intuitive for shorter words to appear first in the suggestion list if they tie in score with neighboring matches.
Maybe, this should be handled in the `.findWordsWithSubsequence` algorithm in superstring by penalizing longer words with the same number of matching characters.
https://github.com/atom/superstring/issues/36
=> Make shorter matches win when scores tie

lib/suggestion-list-element.js, spec/autocomplete-manager-integration-spec.js
Change the rendering logic to render suggestions that aren't initially visible during idle time.
The designs mostly vary around when to do the rendering work that is being deferred. For instance, we could decide to do it on the first scroll event, but this seems like a more complicated implementation.
Rendering latency between keystroke and suggestion list display should be reduced since we are rendering less before painting.
It's harder to test the rendering since `requestIdleCallback` callbacks never get called during testing because we are never idle. :(
n/a
=> Defer the rendering of nonvisible suggestions

lib/suggestion-list-element.js, spec/autocomplete-manager-integration-spec.js, spec/spec-helper.js
This PR defers the rendering of additional suggestions until the user either scrolls the suggestion box or selects a suggestion outside of those initially visible.
Previously, we deferred the rendering until an idle period.
By deferring until the user requests the additional suggestions (basically never) we save ourselves a reflow.
This is slightly more difficult to test since we need to trigger a scroll event to get the rest of the suggestions to render.
n/a
=> Defer rendering nonvisible suggestions until the user scrolls or selects

lib/subsequence-provider.js, spec/subsequence-provider-spec.js
This tidies up a couple remaining issues:
- we now respect the `edtor.nonWordCharacters` config setting
- we never suggest the word under the cursor
fixes https://github.com/atom/autocomplete-plus/issues/901
=> Enhancements in subsequence provider

lib/autocomplete-manager.js, lib/subsequence-provider.js, lib/symbol-provider.js
This will prevent autocomplete-plus from providing its functionality to editors more than once in case they get added to the workspace, then removed from it and finally added back.
/cc: @leroix @nathansobo @jasonrudolph
=> Don't watch the same editor or buffer more than once when re-adding it to the workspace

lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js
Refs https://github.com/atom/atom/pull/16006
Refs https://github.com/atom/text-buffer/pull/273
=> Only use TextBuffer.onDidChangeText, not onDidChange

lib/autocomplete-manager.js, lib/provider-config.js, lib/scope-helpers.js, lib/subsequence-provider.js, lib/suggestion-list-element.js, lib/suggestion-list.js, spec/autocomplete-manager-async-spec.js, spec/autocomplete-manager-integration-spec.js
In this PR, I
- applied caching to hot code paths and eliminated allocations and closures where possible
- reduced the number of matches returned per buffer from 100 to 20 in the subsequence provider
- removed the 50ms delay for displaying suggestions (interferes with the next keystroke)
- dealt with situations where we were rendering outside of an animation frame
- added a `characterMatchIndices` field to suggestions in https://github.com/atom/autocomplete-plus/wiki/Provider-API#suggestions in order to remove unnecessary calls to fuzzalrin
I've tried to optimize for two things in this PR:
1) the time from key character event start to screen paint
2) the idle time between keystrokes (finishing any scripting, rendering, and painting for ac+ well ahead of the next keystroke)
In the image …
=> Optimize the keystroke code path

lib/subsequence-provider.js, spec/subsequence-provider-spec.js
Refs https://github.com/atom/superstring/pull/44
=> Handle findWordsWithSubsequence cancellations

lib/subsequence-provider.js
The default provider was retrieving the global `editor.nonWordCharacters` setting instead of the scoped one when calculating `additionalWordCharacters` to pass to `findWordsWithSubsequence`. 
See:
https://github.com/atom/autocomplete-plus/issues/924
https://github.com/atom/autocomplete-plus/issues/922
https://github.com/atom/autocomplete-plus/issues/920
We still need to ensure the language packages set the proper values for `editor.nonWordCharacters`.
=> Fix additionalWordCharacters bug

lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js, spec/subsequence-provider-spec.js
addendum to https://github.com/atom/autocomplete-plus/pull/928
fixes https://github.com/atom/autocomplete-plus/issues/920
For instance, replacing $foo with the suggestion, $foobar, results in
$$foobar.
This PR makes autocomplete-plus now use `Cursor.getCurrentWordPrefix`
instead of using its own prefix regex. This will help keep things consistent with the `editor.nonWordCharacters` setting.
=> Fix non-word character replacement

keymaps/autocomplete-plus.cson, lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js
There is now a keyboard shortcut (f1) to navigate to More.. in the suggestion list. It goes to the referenced documentation if there is a description block.
There is #717 that wanted to the same, however it didn't go through for some reason and as it is in CoffeScript and an older repo, I don't know why. I took inspiration from #717 and didn't come up with any other approach as it was pretty straight forward.
Access to documentations quicker.
I can't come up with any possible drawbacks.
#567
=> Keybind (f1) to navigate to More.. in the suggestion list.

lib/autocomplete-manager.js, lib/suggestion-list-element.js, lib/suggestion-list.js, spec/provider-api-spec.js, spec/suggestion-list-element-spec.js
This adds an optional hook to the [provider api](https://github.com/atom/autocomplete-plus/wiki/Provider-API):
`.getSuggestionDetailsOnSelect(suggestion)`
This is useful in providers like the language server providers because getting additional details about the suggestion can be expensive.
It takes one of the suggestions previously received via `.getSuggestions` as its argument and returns a `Promise` of a suggestion to replace it with. The `AutocompleteManager` will call this function if it's available on the provider when the user selects or focuses a particular item in the completion list.
I'm on the fence about the name. Internally, we call this action "select", but that sounds like the user is choosing this suggestion. We call choosing the selection "confirming". It could be …
=> Add optional getSuggestionDetailsOnSelect to provider api

spec/symbol-provider-spec.js
Refs https://github.com/atom/atom/pull/13523
=> Avoid querying destroyed editor in SymbolProvider spec

lib/suggestion-list-element.js, package.json
I often found myself pining for the behavior of Sublime Text's autocompletion widget, which permitted navigation with one's arrow keys, à la the "Core Movement Commands" setting here, but wouldn't be so presumptuous as to _hijack_ them and would politely yield control and see itself out if one tried to navigate above its first suggestion or below its last. It was especially handy for breaking out of autocompletion without reaching for <kbd>Escape</kbd>---one could just hit the up arrow and get on with one's life---but it was generally nice not to spend the occasional confused millisecond trying to make the cursor move when a suggestion list was in view.
Implementing the change was super straightforward. There's a new preference, "Cycle Suggestions": in its presence, the behavior is …
=> Optionally dismiss suggestion list on up/down instead of cycling.

lib/autocomplete-manager.js
fix https://github.com/atom/autocomplete-plus/issues/935
=> Remove editor from watchedEditors when editor is destroyed

lib/autocomplete-manager.js, lib/get-additional-word-characters.js, lib/main.js, lib/provider-manager.js, lib/subsequence-provider.js, lib/symbol-provider.js, package.json, spec/autocomplete-manager-integration-spec.js, spec/provider-manager-spec.js, spec/subsequence-provider-spec.js
🍐 d with @maxbrunsfeld 
Autocomplete providers are passed a *prefix* string, which describes the characters preceding the cursor.
Previously, in API v3, this prefix was computed based on a regular expression in this package. It would recognize a fixed set of word characters or a sequence of non-word characters. Unfortunately, this clashed with the fact that different languages have different sets of valid word characters.
When @leroix added the subsequence provider in #886, he introduced the ability to complete words containing symbols, such as `$hello`. Unfortunately, since the *prefix* did not include the leading `$` based on an assumption it was a non-word character, returning a completion of `$hello` would cause a duplication due to the prefix not including the `$`, yielding …
=> Introduce service API version 4.0 with simplified prefix handling

lib/get-additional-word-characters.js, lib/subsequence-provider.js, package.json, spec/subsequence-provider-spec.js
Fixes https://github.com/atom/language-html/issues/184
After landing the new autocomplete subsequence provider, we starting using the `editor.nonWordCharacters` setting to identify words for the purposes of autocomplete. We thought this was improvement over the old strategy that used a hard-coded regex, but it turns out that people expect Atom's word-movement commands to define words differently than autocomplete (see https://github.com/atom/language-html/issues/184).
This PR introduces a *new* setting - `autocomplete.extraWordCharacters` that can be used to further customize the way that we find words for autocomplete. This setting will enable us to revert https://github.com/atom/language-html/commit/4fa8731bf51456ae618379aaceb103d2bc2f0b17, …
=> Add `autocomplete.extraWordCharacters` setting

lib/autocomplete-manager.js
Related to issue 16600 from repo /atom/atom
This issue solves the bug mentioned in [issue](https://github.com/atom/atom/issues/16600). The problem arose because the ```.suggestion-description``` container doesn't exist when the user triggers the command palette, therefore a condition was needed.
Not sure if navigate-to-description-more-link could be removed from the command palette but still work with the key binding, but this would make the functionality harder to find. Open to comments.
The error doesn't pop-up.
Not that I can think of.
[16600](https://github.com/atom/atom/issues/16600)
=> Fix validation issue for navigate-to-description-more-link

lib/suggestion-list-element.js, spec/suggestion-list-element-spec.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Following #838, this PR updates the movement hooks for Page Up/Down and move-to-top/-bottom such that when the `moveToCancel` preference is enabled, the suggestion list is dismissed and the movement command is applied to the editor.
Here's a quick screencast showing the changes in action:
N/A
The principle behind the `moveToCancel` preference was to emulate the behavior of Sublime Text's autocompletion module. Dismissing the suggestion list when the user attempts to navigate "above" or "below" it was one part of that, but my first pass missed the edge …
=> Apply "moveToCancel" preference to all movement commands.

lib/get-additional-word-characters.js, spec/subsequence-provider-spec.js
Fix #956.
https://github.com/atom/autocomplete-plus/blob/edf3db30c04340bbfea1fa5001832e2d16061179/lib/get-additional-word-characters.js#L6
is assigned to `undefined`, because the configuration key is invalid.
Then, `POSSIBLE_WORD_CHARACTERS` that aren’t in `editor.nonWordCharacters` are added at the end of `result`. In JavaScript, concatenating `undefined` and a letter, let’s say '_', produces a string: `"undefined_"`.
The string is then incorporated in the regex there:
https://github.com/atom/autocomplete-plus/blob/edf3db30c04340bbfea1fa5001832e2d16061179/lib/autocomplete-manager.js#L513
As the regex already matches for ASCII letters, this doesn’t cause an issue in the general case.
When you add `_` to `editor.nonWordCharacters`, then `POSSIBLE_WORD_CHARACTERS` and …
=> fix using autocomplete instead of autocomplete-plus to retrieve config

spec/subsequence-provider-spec.js
Removes findWordsWithSubsequence guard and enables spec targeted for Atom 1.22.1 and higher.
Best viewed with ?w=1
Closes #964
=> Cleanup subsequence specs

lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Prevents the suggestion box hiding when a number is typed as part of the prefix
NA
Allows numbers in prefixes to be typed
NA
Fixes #950 
Closes #979 
Fixes https://github.com/autocomplete-python/autocomplete-python/issues/364
Fixes https://github.com/autocomplete-python/autocomplete-python/issues/391
NOTE: I'm not sure if the tests are testing what I expect. It should though, because the change is to `getWordCharacterRegex`, which is used to get valid prefix characters, and the recognised prefix is then tested for.
=> Allow numbers in prefix

lib/suggestion-list-element.js, package.json
This pull request adds support for HTML tags in the description field. Only HTML tags in gfm (GitHub Flavored Markdown) are valid. This approach is heavily based on this piece of code:
https://github.com/sourcegraph/codeintellify/blob/5eef578cfc508dbcc6a97f5ba08675768b0a5187/src/helpers.ts#L90-L102
Using the `dompurify` package instead of the `sanitize-html` package to be consistent with `markdown-preview` for example.
The description text in the LSP package `ide-php` contains HTML. This package currently sanitize the HTML which makes the description look like this:
With this update the description will instead look like this:
N/A
https://github.com/Microsoft/vscode/issues/40607
https://github.com/felixfbecker/php-language-server/issues/674 …
=> Allow GitHub HTML tags in Markdown

spec/autocomplete-manager-integration-spec.js, spec/provider-api-spec.js, spec/spec-helper.js
This PR follows a similar approach than https://github.com/atom/autocomplete-plus/pull/1048 to make the specs more resilient by waiting for specific conditions instead of just sleeping some time.
Hopefully this will address the issue reported in https://github.com/atom/atom/issues/19478
=> Convert Provider API specs to async

spec/autocomplete-manager-async-spec.js, spec/autocomplete-manager-autosave-spec.js, spec/autocomplete-manager-integration-spec.js, spec/autocomplete-manager-undo-spec.js, spec/main-spec.js, spec/provider-api-legacy-spec.js, spec/provider-api-spec.js, spec/spec-helper.js, spec/subsequence-provider-spec.js, spec/suggestion-list-element-spec.js
🍐'd with @rafeca
We're hoping that avoiding Jasmine's queue-based helpers and moving to async/await will help us avoid some flakiness in this package's tests that we've observed since upgrading to Electron 3.1.
We still have about 30 occurrences of `waitsFor` to eliminate in order for the tests to be completely free of reliance Jasmine async helpers.
=> Eliminate use of Jasmine 1.3 async helpers in favor of async/await

lib/autocomplete-manager.js, spec/autocomplete-manager-integration-spec.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Change deprecated `require('shell')` to `require('electron').shell`.
None
Fixes a CI failure for Atom's CI with newer Electron. For example: [CI run](https://dev.azure.com/DeeDeeG/b/_build/results?buildId=930&view=logs&j=c5d9a21a-e43e-5eaa-4a5a-044feacfb7bd&t=1bdeab21-3bba-5fef-2971-1d9f5fd6fff7&l=295)
<details><summary>Error message (click to expand)</summary>
```
Autocomplete Manager
when an external provider is registered
Keybind to navigate to descriptionMoreLink
it Autocomplete Manager when an external provider is registered Keybind to navigate to …
```
=> Update deprecated `require('shell')` to `require('electron').shell` (for Atom's Electron upgrade PR)

package-lock.json, package.json, spec/autocomplete-manager-autosave-spec.js, spec/autocomplete-manager-integration-spec.js, spec/custom-runner.js, spec/provider-api-legacy-spec.js, spec/provider-api-spec.js, spec/spec-helper.js, spec/suggestion-list-element-spec.js
This will replace the default Atom test runner powered by the long outdated Jasmine 1.3 with a new custom test runner powered by the latest Jasmine 3.6.
The documentation of Jasmine 1.3 is very poor, so upgrading the version will allow developers to write tests more efficiently with the new Jasmine docs. It also improves the developer experience because Jasmine 3 is more pleasant to work with.
Not that I can think of any.
=> Upgrade to Jasmine 3

lib/suggestion-list-element.js, package-lock.json, package.json
Equivalent (or rather more simple) than the change at: https://github.com/atom/github/pull/2731
Tests pass: https://github.com/icecream17/autocomplete-plus/actions/runs/1702274127
=> Bump marked from 0.7.0 to 4.0.10
